spring:
  datasource:
    url: jdbc:mysql://localhost:3306/viva
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true